#!/usr/bin/env bash
# scripts/sync-agents.sh
#
# Regenerates each scope's AGENTS.md from its sibling
# .github/copilot-instructions.md so that OpenAI Codex CLI (which reads
# AGENTS.md but does NOT resolve @-imports) sees the same canonical
# content as GitHub Copilot.
#
# Idempotent: re-running on a clean tree produces no diff.
#
# Scopes:
#   - workspace root (.)
#   - every project listed in PROJECTS.md "Production projects" table
#
# Usage: ./scripts/sync-agents.sh [--check]
#   --check : exit non-zero if regeneration would change any file

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

CHECK=0
if [[ "${1:-}" == "--check" ]]; then
  CHECK=1
fi

BANNER_LINE1='<!-- GENERATED by scripts/sync-agents.sh — do not edit. Canonical source: .github/copilot-instructions.md -->'
BANNER_LINE2='<!-- Regenerate with: make sync-agents -->'

# Collect scopes: "." plus every path in the "Production projects" table of PROJECTS.md.
# Table rows look like: | name | `path/` | yes | yes |
scopes=(".")
if [[ -f PROJECTS.md ]]; then
  while IFS= read -r path; do
    [[ -n "$path" ]] || continue
    # strip trailing slash
    scopes+=("${path%/}")
  done < <(awk -F'\\|' '
    /^## Production projects/ { in_table=1; next }
    in_table && /^## / { in_table=0 }
    in_table && NF>=4 && $3 ~ /`/ {
      gsub(/`/, "", $3); gsub(/^ +| +$/, "", $3); print $3
    }
  ' PROJECTS.md)
fi

changed=0
for scope in "${scopes[@]}"; do
  src="$scope/.github/copilot-instructions.md"
  dst="$scope/AGENTS.md"
  if [[ ! -f "$src" ]]; then
    echo "skip: $src (not found)" >&2
    continue
  fi
  tmp="$(mktemp)"
  {
    printf '%s\n' "$BANNER_LINE1"
    printf '%s\n' "$BANNER_LINE2"
    printf '\n'
    cat "$src"
  } > "$tmp"

  if [[ -f "$dst" ]] && cmp -s "$tmp" "$dst"; then
    rm -f "$tmp"
    continue
  fi

  if [[ $CHECK -eq 1 ]]; then
    echo "drift: $dst would be regenerated from $src" >&2
    rm -f "$tmp"
    changed=1
    continue
  fi

  mv "$tmp" "$dst"
  echo "synced: $dst <- $src"
  changed=1
done

if [[ $CHECK -eq 1 && $changed -ne 0 ]]; then
  echo "" >&2
  echo "Drift detected. Run: make sync-agents" >&2
  exit 1
fi

exit 0

