#!/usr/bin/env bash
# .github/scripts/sync-agents.sh
#
# Regenerates AGENTS.md from .github/copilot-instructions.md so that
# OpenAI Codex CLI (which reads AGENTS.md but does NOT resolve @-imports)
# sees the same canonical content as GitHub Copilot.
#
# Idempotent: re-running on a clean tree produces no diff.
#
# Usage: ./.github/scripts/sync-agents.sh [--check] [path ...]
#   --check : exit non-zero if regeneration would change any file
#   path    : additional directories to sync (default: "." only)

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

CHECK=0
scopes=(".")
args=()

for arg in "$@"; do
  case "$arg" in
    --check) CHECK=1 ;;
    *) args+=("${arg%/}") ;;
  esac
done

if [[ ${#args[@]} -gt 0 ]]; then
  scopes+=("${args[@]}")
fi

BANNER_LINE1='<!-- GENERATED by .github/scripts/sync-agents.sh — do not edit. Canonical source: .github/copilot-instructions.md -->'
BANNER_LINE2='<!-- Regenerate with: make sync-agents -->'

changed=0
for scope in "${scopes[@]}"; do
  src="$scope/.github/copilot-instructions.md"
  dst="$scope/AGENTS.md"
  if [[ ! -f "$src" ]]; then
    echo "skip: $src (not found)" >&2
    continue
  fi
  tmp="$(mktemp)"
  {
    printf '%s\n' "$BANNER_LINE1"
    printf '%s\n' "$BANNER_LINE2"
    printf '\n'
    cat "$src"
  } > "$tmp"

  if [[ -f "$dst" ]] && cmp -s "$tmp" "$dst"; then
    rm -f "$tmp"
    continue
  fi

  if [[ $CHECK -eq 1 ]]; then
    echo "drift: $dst would be regenerated from $src" >&2
    rm -f "$tmp"
    changed=1
    continue
  fi

  mv "$tmp" "$dst"
  echo "synced: $dst <- $src"
  changed=1
done

if [[ $CHECK -eq 1 && $changed -ne 0 ]]; then
  echo "" >&2
  echo "Drift detected. Run: make sync-agents" >&2
  exit 1
fi

exit 0
