#!/usr/bin/env bash
# scripts/sync-agents.sh  (ai-dotfiles — single-profile fork)
#
# Deliberate fork of tobevisit/scripts/sync-agents.sh (the canonical,
# multi-scope orchestrator). This copy operates on exactly ONE profile
# directory per invocation and does NOT walk PROJECTS.md.
# Counterpart: tobevisit/scripts/sync-agents.sh
#
# Usage: ./scripts/sync-agents.sh [--profile <name>] [--check]
#   --profile <name> : profile to sync (default: personal)
#   --check          : exit non-zero if regeneration would change the file

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

PROFILE="personal"
CHECK=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile) PROFILE="$2"; shift 2 ;;
    --check)   CHECK=1;       shift   ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

src="$ROOT/profiles/$PROFILE/copilot-instructions.md"
dst="$ROOT/profiles/$PROFILE/AGENTS.md"

if [[ ! -f "$src" ]]; then
  echo "error: $src not found" >&2; exit 1
fi

BANNER_LINE1='<!-- GENERATED by scripts/sync-agents.sh — do not edit. Canonical source: .github/copilot-instructions.md -->'
BANNER_LINE2='<!-- Regenerate with: make sync-agents -->'

tmp="$(mktemp)"
{ printf '%s\n' "$BANNER_LINE1"; printf '%s\n' "$BANNER_LINE2"; printf '\n'; cat "$src"; } > "$tmp"

if [[ -f "$dst" ]] && cmp -s "$tmp" "$dst"; then
  rm -f "$tmp"; exit 0
fi

if [[ $CHECK -eq 1 ]]; then
  echo "drift: $dst would be regenerated from $src" >&2
  rm -f "$tmp"
  echo "" >&2; echo "Drift detected. Run: make sync-agents" >&2
  exit 1
fi

mv "$tmp" "$dst"
echo "synced: $dst <- $src"
