#!/usr/bin/env bash
# .github/scripts/sync-agents.sh
#
# Regenerates three agent-instruction files from _canonical.md so that
# every supported agent reads its own self-contained file with identical
# content:
#
#   CLAUDE.md                        (Claude Code)
#   AGENTS.md                        (OpenAI Codex CLI)
#   .github/copilot-instructions.md  (GitHub Copilot)
#
# Each output gets a GENERATED banner pointing back at _canonical.md.
# Idempotent: re-running on a clean tree produces no diff.
#
# Usage: ./.github/scripts/sync-agents.sh [--check] [path ...]
#   --check : exit non-zero if regeneration would change any file
#   path    : additional scope directories to sync (default: "." only)

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

CHECK=0
scopes=(".")
args=()

for arg in "$@"; do
  case "$arg" in
    --check) CHECK=1 ;;
    *) args+=("${arg%/}") ;;
  esac
done

if [[ ${#args[@]} -gt 0 ]]; then
  scopes+=("${args[@]}")
fi

# Rendered outputs (relative to each scope).
outputs=(
  "CLAUDE.md"
  "AGENTS.md"
  ".github/copilot-instructions.md"
)

emit_banner() {
  printf '%s\n' '<!-- GENERATED by .github/scripts/sync-agents.sh — do not edit. Canonical source: _canonical.md -->'
  printf '%s\n' '<!-- Regenerate with: make sync-agents -->'
  printf '\n'
}

changed=0
for scope in "${scopes[@]}"; do
  src="$scope/_canonical.md"
  if [[ ! -f "$src" ]]; then
    echo "skip: $src (not found)" >&2
    continue
  fi

  for rel in "${outputs[@]}"; do
    dst="$scope/$rel"
    mkdir -p "$(dirname "$dst")"
    tmp="$(mktemp)"
    {
      emit_banner
      cat "$src"
    } > "$tmp"

    if [[ -f "$dst" ]] && cmp -s "$tmp" "$dst"; then
      rm -f "$tmp"
      continue
    fi

    if [[ $CHECK -eq 1 ]]; then
      echo "drift: $dst would be regenerated from $src" >&2
      rm -f "$tmp"
      changed=1
      continue
    fi

    mv "$tmp" "$dst"
    echo "synced: $dst <- $src"
    changed=1
  done
done

if [[ $CHECK -eq 1 && $changed -ne 0 ]]; then
  echo "" >&2
  echo "Drift detected. Run: make sync-agents" >&2
  exit 1
fi

exit 0
